# NumPy Basic
#### This is an approach to learn Numpy. Numpy is a python package that is must for data sciences and image processing. 

## Why it is needed?
#### It basically is a package to manage multi dimensional large datasets. Any image basically is a two dimensional dataset. 
#### So to work with images effectively we need this package


In [3]:
import numpy as np

### Creating a numpy array with all values as zero

In [44]:
myarray = np.zeros((10,10))

In [11]:
myarray

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

### Randomly Generating Some numbers

In [13]:
np.random.seed(101)
arr = np.random.randint(0,100,10)

In [14]:
arr

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [16]:
arr2 = np.random.randint(0,100,10)

In [17]:
arr2

array([ 4, 63, 40, 60, 92, 64,  5, 12, 93, 40])

### Gettin max from a array

In [18]:
arr.max()

95

### Getting index of max value in array

In [19]:
arr.argmax()

0

### Getting index of minimum value in array

In [20]:
arr.argmin()

7

### Getting minimum value from array

In [21]:
arr.min()

9

### Getting shape of array - dimensions of array

In [23]:
arr.shape

(10,)

### Trying to reshape the array. But as array has less then required number of arrays it thorws an error

#### Error is intentional

In [24]:
arr.reshape(10,3)

ValueError: cannot reshape array of size 10 into shape (10,3)

### Ones the parameters are right it reshapes the array
### Reshap means it will make matrix of described number of rows and columns from the given values

In [25]:
arr.reshape(5,2)

array([[95, 11],
       [81, 70],
       [63, 87],
       [75,  9],
       [77, 40]])

### Making a two dimensional array from range 0 to 100 in the shape of 10 rows by 10 columns

In [27]:
matrix = np.arange(100).reshape((10,10))

In [28]:
matrix

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

### Accessing values from array using index

In [30]:
row = 5
col = 5

In [31]:
matrix[row,col]

55

### Getting all the values of column 1 in matrix

In [32]:
matrix[:, 1]

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

### After getting values creating a new array of 5 rows and 2 columns using those values

In [33]:
matrix[:, 1].reshape(5,2)

array([[ 1, 11],
       [21, 31],
       [41, 51],
       [61, 71],
       [81, 91]])

### Getting all values of a row 

In [34]:
matrix[2]

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

### Experimenting different syntexes.  In the bellow cell I was trying to get values of colums using the smae way we took values of rows. But it failed. 

In [35]:
matrix[,2]

SyntaxError: invalid syntax (<ipython-input-35-62819758b6c9>, line 1)

### Getting values of row 0 to 3 and columns 0 to 3

In [36]:
matrix[0:3, 0:3]

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

### Making a copy of existing array

In [40]:
matrix2 = matrix.copy()

In [41]:
matrix2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

### Assigning a particular values to the selected values of the matrix

In [42]:
matrix2[0:3, 0:3] = 0

In [43]:
matrix2

array([[ 0,  0,  0,  3,  4,  5,  6,  7,  8,  9],
       [ 0,  0,  0, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  0,  0, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])